Updating to the latest gradle version
Because:

> General error during conversion: Unsupported class file major version 65
> java.lang.IllegalArgumentException: Unsupported class file major version 65